server:
  port: 9090

spring:
  profiles:
    active: local
  application:
    name: partage
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  #  mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://183.96.35.71:4406/partage?useSSL=false&serverTimezone=Asia/Seoul
    username: ENC(kCK23Aq6Hb3NfP8FQ/Nd4A==)
    password: ENC(pxWqfCD/p9PPsWa12DXBlg==)
  # jpa
  jpa:
    hibernate:
      ddl-auto: update
  # redis - local
  redis:
    port: 6379
    host: localhost
  # mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(tMf8R/oUs6OdZu8pUzdxEkbfo8ajmLf/GyXGx58YvZY=)
    password: ENC(LZLXORicR8sUKCfLueTpyT7tg/0L49D+35QKchswk7GNDJAcet4RWw==)
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true

logging:
  level:
    root: error
    com.egatrap.partage: debug