server:
  port: 9090

spring:
  profiles:
    active: local
  application:
    name: partage
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  #  mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://183.96.35.71:4406/partage?useSSL=false&serverTimezone=Asia/Seoul
    username: ENC(kCK23Aq6Hb3NfP8FQ/Nd4A==)
    password: ENC(pxWqfCD/p9PPsWa12DXBlg==)
  redis:
    host: 183.96.35.71
    port: 4407
    password: ENC(CbbG8fWSz/uTEugdbiMPZQ==)

security:
  jwt:
    secret-key: bWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGk=
    access-token-expire: 300000
    refresh-token-expire: 86400000
  cors:
    allowed-origins: http://localhost:3000

logging:
  level:
    root: error
    com.egatrap.partage: debug