server:
  port: 9090

spring:
  profiles:
    active: local
  application:
    name: partage
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  #  mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(1N4tIi0s/QK1vH/CiRZpz3lomIIywwMO/JO/UAYYh62/S8PT9XVLc0SeGK77rbIKobw2d89z0ZTEsCSW/bNYVS1LD3anBX7GOuLlynJLoYz1ix0zloTc8Q==)
    username: ENC(wFGZw5SUsDHyEmjJh+BMEw==)
    password: ENC(xFPyihZvWivRf2izzSyByjHwV61KFtex)
  # data.sql
  sql:
    init:
      mode: never  # 데이터베이스 초기화 시 always, 이후 never
  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  # redis
  redis:
    #host: localhost
    #port: 6379
    #password:
    host: ENC(eqiZLldyV89XFLbgrHJMPPXLtRB1jgAK)
    port: 6379
    password: zxc123!! #ENC(1taz4+tslq2+0cGhUcH88Q==)
  # mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(tMf8R/oUs6OdZu8pUzdxEkbfo8ajmLf/GyXGx58YvZY=)
    password: ENC(LZLXORicR8sUKCfLueTpyT7tg/0L49D+35QKchswk7GNDJAcet4RWw==)
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true
  # multipart
  servlet:
    multipart:
      max-file-size: 5MB
  # google cloud storage
  cloud:
    gcp:
      storage:
        credentials:
          location: ENC(bHHtGYCsh4p/QR083sy2qLal6Y2XuxTKac5bKqrEj/tekzzEkjOpiAPZR3AFUWYDNApj5BhA798=)
        project-id: ENC(McAhjDuntjazqk6+t/xb62AyHYUF1h31pKh/yLQzLv4=)
        bucket: ENC(HUu0VHh+fSO9J/KwCmORhoaKWc82L6hy)
  # kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat-backup-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



# save path
file:
  profile-images: files/profile-images/

security:
  jwt:
    secret-key: bWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGk=
    #access-token-expire: 300000
    access-token-expire: 86400000
    refresh-token-expire: 86400000
  cors:
    allowed-origins: http://localhost:3000

youtube:
  apikey: ENC(mxSVPKW3rn1s+YYZOmOxKBS3fmRdXy/iKswIpOdjGQ2ty9TzmpBC8bMWrhYxYn7V)

logging:
  level:
    root: error
    com.egatrap.partage: debug