version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "xxxx:xxxx"                       # 포트 설정을 해주세요
    networks:
      - kafka-network
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "xxxx:xxxx"                       # 포트 설정을 해주세요
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka-network
networks:
  kafka-network:
    driver: bridge